name: Flutter Nightly Build

on:
  schedule:
    # schedule build every night
    - cron: '0 0 * * 0'
  workflow_dispatch:
  pull_request:
    branches:
    - main

jobs:
  run-flutter-nightly-build:
    uses: ./.github/workflows/flutter-build.yml
    secrets: inherit
    with:
      upload-artifact: true
      upload-tag: 'nightly'
      node-version: '>=20.x'
